
name: Secret manager
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: google/secrets-sync-action
        with:
          SECRETS: |
            ^FOO$
            ^GITHUB_.*
          REPOSITORIES: |
            Josh-01/test-app-workflow
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS }}
          CONCURRENCY: 10
        env:
          FOO: ${{github.run_id}}
          FOOBAR: BAZ
