# This is a basic workflow to help you get started with Actions

name: Secret manager

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: google/secrets-sync-action@v1.7.0
        with:
          SECRETS: |
            ^FOO$
            ^CONTAINER*
          REPOSITORIES: |
            Josh-01/test-app-workflow
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS }}
          CONCURRENCY: 10
        env:
          FOO: ${{github.run_id}}
          FOOBAR: BAZ
