# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: google/secrets-sync-action
        with:
          SECRETS: |
            ^FOO$
            ^CONTAINER*
          REPOSITORIES: |
            Josh-01/test-app-workflow
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_SECRETS }}
          CONCURRENCY: 10
        env:
          FOO: ${{github.run_id}}
          FOOBAR: BAZ
